apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data-1
  namespace: postgres-operator
  labels:
    type: local
    app: postgres-operator
spec:
  storageClassName: local-storage
  # If a PVC releases claim on this PV, the data will be preserved
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql_1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: application
            operator: In
            values:
              - postgres
